'use client';

import AttachFileRoundedIcon from '@mui/icons-material/AttachFileRounded';
import AutoAwesomeMotionRoundedIcon from '@mui/icons-material/AutoAwesomeMotionRounded';
import ErrorOutlineRoundedIcon from '@mui/icons-material/ErrorOutlineRounded';
import FolderRoundedIcon from '@mui/icons-material/FolderRounded';
import { Avatar, Box, Card, CardActionArea, Chip, Stack, Tooltip, Typography } from '@mui/material';
import React from 'react';
import { TAG_LABEL, TAG_ROLE, TYPE_LABEL } from './constants';
import { TimerChip } from './timer-chip';
import type { DesignCard } from './types';
import { cardSubtitle, promoRange } from './ui-helpers';

/**
 * Tarjeta del tablero. La marca de "Modalidad circular" y la de "Duplicado" van
 * como texto chico y sutil, no como chip: el brief pide que se lean idénticas a
 * un MMS normal.
 */

interface Props {
  card: DesignCard;
  onOpen: (id: string) => void;
  /** La está arrastrando un admin: se levanta con sombra. */
  dragging?: boolean;
}

function CardTileBase({ card, onOpen, dragging = false }: Props): React.JSX.Element {
  const subtitle = cardSubtitle(card);
  const openIssues = card.auditIssues.length;

  return (
    <Card
      variant="outlined"
      sx={{
        borderRadius: 2,
        borderColor: card.tags.includes('prioridad') ? 'error.main' : 'divider',
        // Alto mínimo: con la columna llena las tarjetas no deben achicarse
        // hasta cortar el contenido (el "Modalidad circular" quedaba truncado).
        minHeight: 138,
        boxShadow: dragging ? 6 : 0,
        transition: 'box-shadow .15s ease',
      }}
    >
      <CardActionArea
        onClick={() => onOpen(card.id)}
        sx={{ p: 1.5, alignItems: 'stretch', height: '100%' }}
      >
        <Stack spacing={1}>
          <Stack
            direction="row"
            justifyContent="space-between"
            alignItems="flex-start"
            spacing={1}
          >
            <Box sx={{ minWidth: 0 }}>
              <Typography
                variant="subtitle2"
                fontWeight={700}
                noWrap
              >
                {card.storeName}
              </Typography>
              {subtitle && (
                <Typography
                  variant="caption"
                  color="text.disabled"
                  sx={{
                    fontSize: 10.5,
                    display: 'block',
                    lineHeight: 1.2,
                    whiteSpace: 'nowrap',
                  }}
                >
                  {subtitle}
                </Typography>
              )}
            </Box>
            {card.designerName && (
              <Tooltip title={`Diseñador: ${card.designerName}`}>
                <Avatar sx={{ width: 26, height: 26, fontSize: 12 }}>
                  {card.designerName.charAt(0)}
                </Avatar>
              </Tooltip>
            )}
          </Stack>

          <Typography
            variant="caption"
            color="text.secondary"
            noWrap
          >
            {promoRange(card)} · {card.productCount} prod.
          </Typography>

          <Stack
            direction="row"
            spacing={0.5}
            flexWrap="wrap"
            useFlexGap
            alignItems="center"
          >
            <Chip
              size="small"
              label={TYPE_LABEL[card.type]}
              variant="filled"
              color={card.type === 'especial' ? 'secondary' : 'default'}
              sx={{ height: 20, fontSize: 10.5 }}
            />
            {card.tags.map((tag) => (
              <Chip
                key={tag}
                size="small"
                label={TAG_LABEL[tag]}
                color={TAG_ROLE[tag] === 'secondary' ? 'default' : TAG_ROLE[tag]}
                variant="outlined"
                sx={{ height: 20, fontSize: 10.5 }}
              />
            ))}
          </Stack>

          <Stack
            direction="row"
            spacing={0.75}
            alignItems="center"
          >
            <TimerChip card={card} />
            {card.folderUrl && (
              <Tooltip title="Carpeta creada">
                <FolderRoundedIcon
                  fontSize="small"
                  color="success"
                />
              </Tooltip>
            )}
            {card.attachments.length > 0 && (
              <Tooltip title={`${card.attachments.length} adjunto(s)`}>
                <AttachFileRoundedIcon
                  fontSize="small"
                  color="disabled"
                />
              </Tooltip>
            )}
            {card.autoGenerated && (
              <Tooltip title="Generada por la automatización semanal">
                <AutoAwesomeMotionRoundedIcon
                  fontSize="small"
                  color="disabled"
                />
              </Tooltip>
            )}
            {openIssues > 0 && (
              <Tooltip title={`${openIssues} error(es) de auditoría`}>
                <Stack
                  direction="row"
                  alignItems="center"
                  spacing={0.25}
                >
                  <ErrorOutlineRoundedIcon
                    fontSize="small"
                    color="error"
                  />
                  <Typography
                    variant="caption"
                    color="error"
                    fontWeight={700}
                  >
                    {openIssues}
                  </Typography>
                </Stack>
              </Tooltip>
            )}
          </Stack>
        </Stack>
      </CardActionArea>
    </Card>
  );
}

export const CardTile = React.memo(CardTileBase);

export default CardTile;
