/**
 * Semilla de fase 1.
 *
 * Ojo con el alcance: las TIENDAS y los EMPLEADOS ya no se inventan acá — salen
 * de la plataforma (ver `use-design-data.ts`). Lo que queda es el equipo de
 * diseño (configurable desde el módulo) y las tarjetas de demostración, que sí
 * son ficticias hasta que exista el backend.
 */
import type { CircularConfig, DesignCard, DesignUser } from './types';

/** Pedro y María: admins con todos los permisos. El área sólo define con qué
 *  autoría se firman los errores de auditoría. */
export const ADMINS: DesignUser[] = [
  { id: 'u-pedro', name: 'Pedro', role: 'admin', area: 'diseño' },
  { id: 'u-maria', name: 'María', role: 'admin', area: 'contenido' },
];

/** Equipo de diseño inicial. Se puede editar desde Configuración › Diseñadores. */
export const DEFAULT_DESIGNERS: DesignUser[] = [
  { id: 'd-justin', name: 'Justin Garcia', role: 'designer' },
  { id: 'd-juan', name: 'Juan Vasquez', role: 'designer' },
  { id: 'd-fernando', name: 'Fernando Melendez', role: 'designer' },
  { id: 'd-keily', name: 'Keily Matute', role: 'designer' },
];

/* ── Helpers de fechas relativas ───────────────────────────────────────── */

const now = Date.now();
const DAY = 24 * 60 * 60 * 1000;

const at = (minutesAgo: number): string => new Date(now - minutesAgo * 60_000).toISOString();
const day = (offset: number): string => new Date(now + offset * DAY).toISOString().slice(0, 10);

/* ── Lista de productos de ejemplo (formato real del cliente) ──────────── */

const asHtml = (lines: string[]): string =>
  lines.map((line) => (line === '' ? '<div><br></div>' : `<div>${line}</div>`)).join('');

const SAMPLE_LIST = asHtml([
  'GREEN GIANT',
  'IDAHO POTATOES',
  '5 LB BAG',
  '$1.99 EA',
  'REG $3.99 EA',
  '',
  'SNAPPLE',
  'TEA OR JUICE',
  'ASSORTED VARIETIES',
  '64 FL OZ BTL',
  '2/$3.00',
  'REG $3.29 EA',
  '',
  'TALENTI',
  'GELATO OR SORBETO',
  'ASSORTED VARIETIES',
  'EXCLUDES LAYERS',
  '16 FL OZ CONT',
  '2/$8.00',
  'REG $7.29 EA',
  'WITH CLUB CARD',
  'LIMIT 2 OFFERS PER FAMILY',
  'MUST BUY 2',
  '',
  'BOAR&#39;S HEAD',
  'OVENGOLD TURKEY',
  'SLICED TO ORDER',
  '$7.99 LB',
  'REG $9.99 LB',
  '',
  'CORONA EXTRA',
  '12 PACK 144 FL OZ',
  'PLUS DEPOSIT WHERE APPLICABLE',
  '$16.99',
  'REG $23.99',
]);

const SHORT_LIST = asHtml([
  'LAY&#39;S POTATO CHIPS',
  'ASSORTED VARIETIES',
  '7.75 OZ BAG',
  '2/$7.00',
  'REG $4.99 EA',
]);

/* ── Fábrica de tarjetas ───────────────────────────────────────────────── */

let seq = 0;
const nextId = (): string => `card-${++seq}`;

/**
 * Tiendas de las tarjetas de demostración. Son texto suelto a propósito: las
 * tarjetas nuevas toman la tienda del listado real de la plataforma, pero la
 * semilla no puede depender de ids que sólo existen en la base.
 */
interface DemoStore {
  name: string;
  address: string;
}

const DEMO_STORES: DemoStore[] = [
  { name: 'Super Supermarket', address: '30 Memorial Dr, Paterson, NJ 07505' },
  { name: 'City Supermarket', address: '145 Main St, Newark, NJ 07102' },
  { name: 'Fine Fare Brentwood', address: '890 Suffolk Ave, Brentwood, NY 11717' },
  { name: 'Key Food Bronx', address: '2405 Grand Concourse, Bronx, NY 10468' },
  { name: 'Extra Supermarket', address: '77 Market St, Passaic, NJ 07055' },
  { name: 'Shop Fair Jamaica', address: '160-10 Jamaica Ave, Queens, NY 11432' },
  { name: 'Met Foodmarket', address: '512 Bergenline Ave, Union City, NJ 07087' },
  { name: 'Compare Foods', address: '1250 Southern Blvd, Bronx, NY 10459' },
];

type CardSeed = Partial<DesignCard> & { store: number };

function makeCard(seed: CardSeed): DesignCard {
  const { store, ...rest } = seed;
  const demo = DEMO_STORES[store] ?? DEMO_STORES[0];
  const base: DesignCard = {
    id: nextId(),
    type: 'mms',
    status: 'nuevo_requerimiento',
    storeId: '',
    storeName: demo.name,
    address: demo.address,
    promoStart: day(1),
    promoEnd: day(7),
    designerId: null,
    designerName: null,
    productCount: 6,
    tags: [],
    productList: '',
    attachments: [],
    brief: '',
    briefImages: [],
    requesterId: null,
    requesterName: null,
    shelfsignsCount: 0,
    tabletVersions: 0,
    folderUrl: null,
    isDuplicate: false,
    duplicatedFromId: null,
    auditIssues: [],
    auditRound: 1,
    errorPeriods: [],
    holdPeriods: [],
    timestamps: {
      createdAt: at(1440),
      assignedAt: null,
      designStartedAt: null,
      sentToAuditAt: null,
      approvedAt: null,
      scheduledAt: null,
    },
    autoGenerated: false,
  };
  return { ...base, ...rest, timestamps: { ...base.timestamps, ...(rest.timestamps ?? {}) } };
}

const assignTo = (designerId: string) => {
  const d = DEFAULT_DESIGNERS.find((x) => x.id === designerId);
  return { designerId: d?.id ?? null, designerName: d?.name ?? null };
};

export function buildMockCards(): DesignCard[] {
  seq = 0;
  return [
    /* Nuevo requerimiento */
    makeCard({
      store: 0,
      status: 'nuevo_requerimiento',
      productCount: 8,
      tags: ['prioridad'],
      timestamps: { createdAt: at(90) } as DesignCard['timestamps'],
    }),
    makeCard({
      store: 2,
      status: 'nuevo_requerimiento',
      type: 'mms_circular',
      autoGenerated: true,
      productCount: 6,
      timestamps: { createdAt: at(200) } as DesignCard['timestamps'],
    }),

    /* Productos definidos */
    makeCard({
      store: 1,
      status: 'productos_definidos',
      productCount: 5,
      tags: ['lista_creada', 'shelfsigns'],
      shelfsignsCount: 5,
      productList: SHORT_LIST,
      ...assignTo('d-justin'),
      timestamps: { createdAt: at(400), assignedAt: at(120) } as DesignCard['timestamps'],
    }),

    /* Diseñándose — cronómetro corriendo */
    makeCard({
      store: 3,
      status: 'disenandose',
      productCount: 10,
      tags: ['lista_creada'],
      productList: SAMPLE_LIST,
      folderUrl: 'https://drive.google.com/drive/folders/mock-key-food',
      ...assignTo('d-juan'),
      timestamps: {
        createdAt: at(600),
        assignedAt: at(300),
        designStartedAt: at(38),
      } as DesignCard['timestamps'],
    }),

    /* On Hold — pausada ahora, el cronómetro debe estar congelado */
    makeCard({
      store: 4,
      status: 'on_hold',
      productCount: 14,
      tags: ['lista_creada', 'shelfsigns'],
      shelfsignsCount: 14,
      productList: SAMPLE_LIST,
      ...assignTo('d-keily'),
      holdPeriods: [{ start: at(25), end: null }],
      timestamps: {
        createdAt: at(800),
        assignedAt: at(500),
        designStartedAt: at(95),
      } as DesignCard['timestamps'],
    }),

    /* Auditoría */
    makeCard({
      store: 5,
      status: 'auditoria',
      productCount: 6,
      tags: ['lista_creada'],
      productList: SHORT_LIST,
      folderUrl: 'https://drive.google.com/drive/folders/mock-shop-fair',
      tabletVersions: 3,
      ...assignTo('d-justin'),
      timestamps: {
        createdAt: at(900),
        assignedAt: at(700),
        designStartedAt: at(120),
        sentToAuditAt: at(78),
      } as DesignCard['timestamps'],
    }),

    /* Errores / Updates — error del diseñador, con checklist de los dos admins */
    makeCard({
      store: 6,
      status: 'errores_updates',
      productCount: 4,
      tags: ['lista_creada'],
      productList: SHORT_LIST,
      ...assignTo('d-juan'),
      auditRound: 2,
      auditIssues: [
        {
          id: 'iss-1',
          description: '<div>Falta el logo de la tienda en la esquina inferior derecha.</div>',
          authorId: 'u-pedro',
          authorName: 'Pedro',
          area: 'diseño',
          createdAt: at(180),
          round: 1,
        },
        {
          id: 'iss-2',
          description: '<div>“Ofertas válidas” está escrito “Ofertas balidas”.</div>',
          authorId: 'u-maria',
          authorName: 'María',
          area: 'contenido',
          createdAt: at(175),
          round: 1,
        },
      ],
      errorPeriods: [{ cause: 'error_disenador', start: at(175), end: null }],
      timestamps: {
        createdAt: at(1200),
        assignedAt: at(1000),
        designStartedAt: at(320),
        sentToAuditAt: at(285),
      } as DesignCard['timestamps'],
    }),

    /* Esperando aprobación */
    makeCard({
      store: 7,
      status: 'esperando_aprobacion',
      productCount: 20,
      tags: ['lista_creada', 'shelfsigns'],
      shelfsignsCount: 20,
      productList: SAMPLE_LIST,
      folderUrl: 'https://drive.google.com/drive/folders/mock-compare',
      tabletVersions: 5,
      ...assignTo('d-keily'),
      timestamps: {
        createdAt: at(1500),
        assignedAt: at(1400),
        designStartedAt: at(400),
        sentToAuditAt: at(315),
      } as DesignCard['timestamps'],
    }),

    /* Diseño Especial en curso */
    makeCard({
      store: 0,
      status: 'disenandose',
      type: 'especial',
      productCount: 0,
      brief:
        'Banner para el sorteo del Día de las Madres. Tonos pastel, foto de familia, sin precios.',
      requesterId: 'demo-requester',
      requesterName: 'Daniela Rojas',
      ...assignTo('d-fernando'),
      timestamps: {
        createdAt: at(300),
        assignedAt: at(200),
        designStartedAt: at(22),
      } as DesignCard['timestamps'],
    }),

    /* Duplicado de otra dirección */
    makeCard({
      store: 1,
      status: 'finalizado',
      productCount: 6,
      isDuplicate: true,
      duplicatedFromId: 'card-3',
      tags: ['lista_creada'],
      productList: SHORT_LIST,
      tabletVersions: 2,
      ...assignTo('d-justin'),
      timestamps: {
        createdAt: at(2000),
        assignedAt: at(1900),
        designStartedAt: at(1500),
        sentToAuditAt: at(1465),
        approvedAt: at(1400),
      } as DesignCard['timestamps'],
    }),

    /* Finalizado a tiempo, generado por la automatización */
    makeCard({
      store: 2,
      status: 'finalizado',
      type: 'mms_circular',
      autoGenerated: true,
      productCount: 8,
      tags: ['lista_creada', 'shelfsigns'],
      shelfsignsCount: 8,
      productList: SAMPLE_LIST,
      tabletVersions: 4,
      ...assignTo('d-juan'),
      timestamps: {
        createdAt: at(3000),
        assignedAt: at(2900),
        designStartedAt: at(2600),
        sentToAuditAt: at(2558),
        approvedAt: at(2500),
      } as DesignCard['timestamps'],
    }),

    /* Agendado */
    makeCard({
      store: 4,
      status: 'agendado',
      productCount: 10,
      tags: ['lista_creada'],
      productList: SAMPLE_LIST,
      tabletVersions: 3,
      ...assignTo('d-keily'),
      timestamps: {
        createdAt: at(4000),
        assignedAt: at(3900),
        designStartedAt: at(3600),
        sentToAuditAt: at(3540),
        approvedAt: at(3500),
        scheduledAt: at(3400),
      } as DesignCard['timestamps'],
    }),

    /* Fuera de tiempo y con un error: el dashboard necesita los tres colores */
    makeCard({
      store: 5,
      status: 'finalizado',
      productCount: 4,
      tags: ['lista_creada'],
      productList: SHORT_LIST,
      ...assignTo('d-fernando'),
      auditIssues: [
        {
          id: 'iss-3',
          description: '<div>Fechas de vigencia equivocadas.</div>',
          authorId: 'u-maria',
          authorName: 'María',
          area: 'contenido',
          createdAt: at(2200),
          round: 1,
        },
      ],
      timestamps: {
        createdAt: at(2600),
        assignedAt: at(2500),
        designStartedAt: at(2400),
        sentToAuditAt: at(2345),
        approvedAt: at(2200),
      } as DesignCard['timestamps'],
    }),
  ];
}

/**
 * Arranca sin grupos: las tiendas se eligen del listado real de la plataforma
 * desde Configuración › Modalidad circular.
 */
export const DEFAULT_CIRCULAR_CONFIG: CircularConfig = {
  enabled: true,
  defaultDay: 1,
  groups: [],
  lastRunAt: null,
};
